server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    Swap for prod
    url: jdbc:postgresql://localhost:5432/linkedin
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: DEBUG